### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Vasolix** [KiwiTerra/Status#1]
(node:1365) UnhandledPromiseRejectionWarning: TypeError: Object.entries(...).filter(...).flatMap is not a function
    at new APIRequest (/home/Bots/node_modules/discord.js/src/rest/APIRequest.js:24:10)
    at RESTManager.request (/home/Bots/node_modules/discord.js/src/rest/RESTManager.js:39:24)
    at Proxy.options (/home/Bots/node_modules/discord.js/src/rest/APIRouter.js:30:19)
    at MessageManager._fetchMany (/home/Bots/node_modules/discord.js/src/managers/MessageManager.js:140:75)
    at MessageManager.fetch (/home/Bots/node_modules/discord.js/src/managers/MessageManager.js:68:86)
    at Timeout.refresh [as _onTimeout] (/home/Bots/src/index.js:75:39)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1365) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1365) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Help me plz

**Comment by AiwunOfficiel** [comment]
Hello, what is your version of discordJS and nodejs ?
